# Generated by Django 5.2.15 on 2026-06-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence_connectee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConnectedDevice',
            new_name='SmartDevice',
        ),
    ]
