# Generated by Django 6.0.3 on 2026-04-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence_connectee', '0002_alter_etudiant_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='num_etudiant',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
    ]
