# Generated by Django 5.2.15 on 2026-06-30 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence_connectee', '0002_rename_connecteddevice_smartdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('study_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='residence_connectee.studyroom')),
            ],
        ),
        migrations.DeleteModel(
            name='RoomReservation',
        ),
    ]
