# Generated by Django 6.0.3 on 2026-04-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence_connectee', '0003_etudiant_age_etudiant_num_etudiant_etudiant_sexe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='telephone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='sexe',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='num_etudiant',
            new_name='student_id',
        ),
    ]
