# Generated by Django 5.2.13 on 2026-04-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence_connectee', '0004_rename_telephone_etudiant_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
