# Generated by Django 5.2.13 on 2026-04-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence_connectee', '0006_alter_etudiant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='points_connexion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='points_consultation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
