# Generated by Django 5.2.13 on 2026-04-18 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence_connectee', '0007_etudiant_points_connexion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('numero_logement', models.CharField(max_length=10)),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Cuisine', 'Cuisine'), ('Salon', 'Salon'), ('Chambre', 'Chambre'), ('SDB', 'Salle de Bain')], max_length=50)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='residence_connectee.logement')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetConnecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_objet', models.CharField(blank=True, choices=[('Lampe', 'Lampe'), ('Thermostat', 'Thermostat'), ('Prise', 'Prise')], max_length=50, null=True)),
                ('etat', models.BooleanField(default=False)),
                ('consommation', models.FloatField(default=0.0)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objets', to='residence_connectee.piece')),
            ],
        ),
    ]
