# Generated by Django 5.2.13 on 2026-04-18 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence_connectee', '0008_logement_piece_objetconnecte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('categorie', models.CharField(choices=[('RESIDENCE', 'Vie de la résidence'), ('LOCAL', 'Infos Locales'), ('URGENT', 'Alerte / Maintenance')], default='RESIDENCE', max_length=50)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
    ]
