# Generated by Django 5.2.13 on 2026-04-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence_connectee', '0009_actualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='niveau',
            field=models.CharField(choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Avancé', 'Avancé'), ('Expert', 'Expert')], default='Débutant', max_length=20),
        ),
    ]
