# Generated by Django 5.2.13 on 2026-04-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence_connectee', '0011_salleetude_reservationsalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetconnecte',
            name='connectivite',
            field=models.CharField(blank=True, choices=[('Wi-Fi', 'Wi-Fi'), ('Bluetooth', 'Bluetooth'), ('Zigbee', 'Zigbee')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='derniere_interaction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='marque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='niveau_batterie',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
